"""add orders and counteragents tables

Revision ID: 292db433d58c
Revises: 
Create Date: 2023-04-12 14:47:51.182661

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "292db433d58c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "counteragents",
        sa.Column("time", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("time"),
        sa.UniqueConstraint("time"),
    )
    op.create_table(
        "orders",
        sa.Column("time", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("time"),
        sa.UniqueConstraint("time"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    op.drop_table("counteragents")
    # ### end Alembic commands ###
