name: Styles

on: [push, pull_request]

jobs:
  formatter_and_linter_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.1

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install black
        pip install -r ./bot/requirements.txt 

    - name: Test with flake8 and black
      run: |
        python -m black .